baseurl = "https://zurasta.com"
title = "zurasta"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true
publishDir = "docs"

[params]
  title = "zurasta"
  description = 'Feel good about food' #todo: slogan
  logo = "fa-diamond"
  copyright = "zurasta"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "zurasta"
